### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by workx247** [Unpluralized/PyAE#1]
Dear programmer Unpluralized,

we are happy to see that people are using python to analyse acoustic emission data.
We would like to contribute and help to further develop the library.
Maybe not under GPL, but some license without copyleft properties, e.g. MIT
Is there any way we could contact you?

**Comment by Unpluralized** [comment]
Hi, 

I appreciate you even finding my code and showing an interest in it. I do receive messages on here, so initially you can ask your questions here.

I would like to understand your interest and its purpose. Do you mind sharing who you are and in what context/application you are interested in AE or my code?

Best, 
Bastiaan

**Comment by workx247** [comment]
Hello,

my name is Daniel, working at Vallen Systeme. But I am not speaking as a private person - this is my private github account, though.

We simply would like to contribute to a repository of Python code, usable to deal with our databases, as many customers of ours, and also some universities, do lots of R&D with our equipment.

It is part of our company culture to help our customers, also with very specific frameworks. But as Python is very common, dominant so to say, and lots of requests have a Python context, we think it makes sense to have a single authority/source out there on the web than just the Python code we maintain in-house.

This is interesting for some reasons:

1) We would have a single outpost where we could direct all the requests. Also a public forum for discussions on improvements and bugs on the code.
3) People would have the opportunity to contribute and shape the framework instead of just accepting what we (I) have done so far (it is basically just me who gives Python support).
4) Not everybody would have to re-invent the wheel.
5) As the database format changes from time to time, old code breaks. For instance our latest change, lossless compression of the transient data, would only be noticed by Python users through strange code behavior. We could engage in the discussion in advance and make our open file format even more open and accessible without any surprises (we don't want anybody to stumble upon our changes, but we have no forum yet and of course some changes really make sense, like the compression just mentioned - just to be clear here: we implemented this feature/change as a customer request, not because we think it might be funny to break old code ^^).

I would really appreciate a non-public conversation at first and not letting my private account get to much involved. I would appreciate an email to info@vallen.de
(https://www.vallen.de/contact/)

Sincerely
Daniel
